spring:
  application:
    name: comercial-pereira-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:comercial_pereira}
    username: ${DB_USER:comercial_user}
    password: ${DB_PASSWORD:comercial_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    timeout: 2000ms
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0

  security:
    jwt:
      secret: ${JWT_SECRET:comercial-pereira-jwt-secret-key-very-long-and-secure}
      expiration: ${JWT_EXPIRATION:86400000} # 24 horas

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    br.com.comercialpereira: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Configurações customizadas
comercial:
  business:
    cnpj: "00.009.295/0001-67"
    name: "Comercial Pereira José Leandro Cassiano Pereira"
    min-stock-alert-days: 7
    max-file-size: 10MB

  api:
    version: v1
    base-path: /api/v1

  cache:
    ttl:
      products: 300 # 5 minutos
      categories: 600 # 10 minutos
      customers: 180 # 3 minutos